### ISSUE TITLE
Error while evaluation (running build_ext)

### ISSUE THREAD

**Issue by dmhyun** [MANGA-UOFA/NAUS#2]
I've tried to evaluate the model with the below command

```
CUDA_VISIBLE_DEVICES=0 python fairseq_cli/generate.py data-bin/gigaword_10 --seed 17 --source-lang article --target-lang summary --path model_weights/HC_10_length_control.pt  --task summarization --scoring rouge --arch nat_encoder_only_ctc --gen-subset test
```

Then, it produces the following error.

```
2022-04-28 17:22:47 | INFO | fairseq.tasks.summarization | [article] dictionary: 115631 types
2022-04-28 17:22:47 | INFO | fairseq.tasks.summarization | [summary] dictionary: 115631 types
2022-04-28 17:22:47 | INFO | fairseq_cli.generate | loading model(s) from model_weights/HC_10_length_control.pt
data-bin/gigaword_10/test.article-summary.article
2022-04-28 17:22:48 | INFO | fairseq.data.data_utils | loaded 1,951 examples from: data-bin/gigaword_10/test.article-summary.article
2022-04-28 17:22:48 | INFO | fairseq.data.data_utils | loaded 1,951 examples from: data-bin/gigaword_10/test.article-summary.summary
2022-04-28 17:22:48 | INFO | fairseq.tasks.summarization | data-bin/gigaword_10 test article-summary 1951 examples
Traceback (most recent call last):
  File "/home/users/dongmin/NAUS/fairseq/data/data_utils.py", line 312, in batch_by_size
    from fairseq.data.data_utils_fast import (
  File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
    # cython: language_level=3
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fairseq_cli/generate.py", line 472, in <module>
    cli_main()
  File "fairseq_cli/generate.py", line 468, in cli_main
    main(args)
  File "fairseq_cli/generate.py", line 52, in main
    return _main(cfg, sys.stdout)
  File "fairseq_cli/generate.py", line 143, in _main
    itr = task.get_batch_iterator(
  File "/home/users/dongmin/NAUS/fairseq/tasks/fairseq_task.py", line 295, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "/home/users/dongmin/NAUS/fairseq/data/fairseq_dataset.py", line 145, in batch_by_size
    return data_utils.batch_by_size(
  File "/home/users/dongmin/NAUS/fairseq/data/data_utils.py", line 323, in batch_by_size
    raise ValueError(
ValueError: Please build (or rebuild) Cython components with `python setup.py build_ext --inplace`.
```

When I build Cython components in this repository directory, I get the following error.

```
$ python setup.py build_ext --inplace

(many lines above...)
building 'alignment_train_cpu_binding' extension
gcc -pthread -B /opt/anaconda3/2021.05/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/users/dongmin/.local/lib/python3.8/site-packages/torch/include -I/home/users/dongmin/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/users/dongmin/.local/lib/python3.8/site-packages/torch/include/TH -I/home/users/dongmin/.local/lib/python3.8/site-packages/torch/include/THC -I/opt/anaconda3/2021.05/include/python3.8 -c examples/operators/alignment_train_cpu.cpp -o build/temp.linux-x86_64-3.8/examples/operators/alignment_train_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=alignment_train_cpu_binding -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
gcc: error: examples/operators/alignment_train_cpu.cpp: No such file or directory
error: command 'gcc' failed with exit status 1
```

Is there any solution to this error? Thanks in advance.

**Comment by puyuanliu** [comment]
Thank you for reporting the issue! This seems to be some incompatibility between your environment and Fairseq. 
Could you test whether the plain Fairseq is working in your environment?

**Comment by dmhyun** [comment]
It works well now. I reinstalled the repository, and then the problem did not appear anymore. Thanks.
